// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATBASDaSF22OkTOhB0xpeGaM5Zifye0nE',
    appId: '1:188038404979:web:38f917b9212010b71b0306',
    messagingSenderId: '188038404979',
    projectId: 'wirenews-17f35',
    authDomain: 'wirenews-17f35.firebaseapp.com',
    storageBucket: 'wirenews-17f35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTscXCEJ8N4LWcKqjIeOSj7wemH_C2-U',
    appId: '1:188038404979:android:fe99b04140e1a9b71b0306',
    messagingSenderId: '188038404979',
    projectId: 'wirenews-17f35',
    storageBucket: 'wirenews-17f35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRsK0WPEL3hPZP_FAgVTrJlAxNhBcNDAw',
    appId: '1:188038404979:ios:62b051a5d3df481c1b0306',
    messagingSenderId: '188038404979',
    projectId: 'wirenews-17f35',
    storageBucket: 'wirenews-17f35.firebasestorage.app',
    iosBundleId: 'com.example.wirenews',
  );
}
